// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package account

import (
	"logbook/cmd/account/endpoints"
	"net/http"
)

type Interface interface {
	CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error) {
	return nil, nil
}
