// Code generated by gohandlers v0.31.0. DO NOT EDIT.

package registration

import (
	"logbook/cmd/registration/endpoints"
	"net/http"
)

type Interface interface {
	CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error)
	CreateEmailGrant(*endpoints.CreateEmailGrantRequest) (*endpoints.CreateEmailGrantResponse, error)
	CreatePasswordGrant(*endpoints.CreatePasswordGrantRequest) (*endpoints.CreatePasswordGrantResponse, error)
	CreatePhoneGrant(*endpoints.CreatePhoneGrantRequest) (*endpoints.CreatePhoneGrantResponse, error)
}

type Mock struct {
}

func (m *Mock) CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) CreateEmailGrant(*endpoints.CreateEmailGrantRequest) (*endpoints.CreateEmailGrantResponse, error) {
	return nil, nil
}

func (m *Mock) CreatePasswordGrant(*endpoints.CreatePasswordGrantRequest) (*endpoints.CreatePasswordGrantResponse, error) {
	return nil, nil
}

func (m *Mock) CreatePhoneGrant(*endpoints.CreatePhoneGrantRequest) (*endpoints.CreatePhoneGrantResponse, error) {
	return nil, nil
}
