// Code generated by gohandlers v0.16.0. DO NOT EDIT.

package registration

import (
	"logbook/cmd/registration/endpoints"
	"net/http"
)

type Interface interface {
	CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error) {
	return nil, nil
}
