all: \
	anti-csrf-token-generation.png \
	uss.png \
	service-discovery.png \
	placement-cache.png

service-discovery.png: service-discovery.mmd
	mmdc -f -e png -s 3 -i "service-discovery.mmd" -o "service-discovery.png"

uss.png: uss.mmd
	mmdc -f -e png -s 3 -i "uss.mmd" -o "uss.png"

anti-csrf-token-generation.png: anti-csrf-token-generation.mmd
	mmdc -f -e png -s 3 -i "anti-csrf-token-generation.mmd" -o "anti-csrf-token-generation.png"

placement-cache.png: placement-cache.mmd
	mmdc -f -e png -s 3 -i "placement-cache.mmd" -o "placement-cache.png"
