// Code generated by govalid. DO NOT EDIT.

package incoming

import "fmt"

func (m MemberType) Validate() error {
	switch m {
	case GroupTypeMember:
		return nil
	case UserTypeMember:
		return nil
	}
	return fmt.Errorf("invalid value")
}
