// Code generated by govalid. DO NOT EDIT.

package incoming

import "fmt"

func (p PolicyAction) Validate() error {
	switch p {
	case Read:
		return nil
	case Write:
		return nil
	}
	return fmt.Errorf("invalid value")
}
