// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"OidGid": {Method: "GET", Path: "/oid-gid/{action}/{gid}/{oid}", Ref: pr.OidGid},
		"OidUid": {Method: "GET", Path: "/oid-uid/{action}/{oid}/{uid}", Ref: pr.OidUid},
	}
}
