// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq OidGidRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Action.Validate(); err != nil {
		errs["action"] = err
	}
	if err := bq.Actor.Validate(); err != nil {
		errs["gid"] = err
	}
	if err := bq.Resource.Validate(); err != nil {
		errs["oid"] = err
	}
	return
}

func (bq OidUidRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Action.Validate(); err != nil {
		errs["action"] = err
	}
	if err := bq.Actor.Validate(); err != nil {
		errs["uid"] = err
	}
	if err := bq.Resource.Validate(); err != nil {
		errs["oid"] = err
	}
	return
}
