// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

func (bq OidGidRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Action.Validate(); issue != nil {
		issues["action"] = issue
	}
	if issue := bq.Actor.Validate(); issue != nil {
		issues["gid"] = issue
	}
	if issue := bq.Resource.Validate(); issue != nil {
		issues["oid"] = issue
	}
	return
}

func (bq OidUidRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Action.Validate(); issue != nil {
		issues["action"] = issue
	}
	if issue := bq.Actor.Validate(); issue != nil {
		issues["uid"] = issue
	}
	if issue := bq.Resource.Validate(); issue != nil {
		issues["oid"] = issue
	}
	return
}
