// Code generated by gonfique. DO NOT EDIT.

package local

import (
	"fmt"
	"gopkg.in/yaml.v3"
	"os"
)

type Local struct {
	Accounts   []string `yaml:"accounts"`
	Discovery  []string `yaml:"discovery"`
	Internal   []string `yaml:"internal"`
	Objectives []string `yaml:"objectives"`
}

func ReadLocal(path string) (*Local, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening config file: %w", err)
	}
	defer file.Close()
	l := &Local{}
	err = yaml.NewDecoder(file).Decode(l)
	if err != nil {
		return nil, fmt.Errorf("decoding config file: %w", err)
	}
	return l, nil
}
