// Code generated by gonfique. DO NOT EDIT.

package local

import (
	"fmt"
	"gopkg.in/yaml.v3"
	"os"
)

type Accounts []string
type Discovery []string
type Objectives []string
type Local struct {
	Accounts   Accounts   `yaml:"accounts"`
	Discovery  Discovery  `yaml:"discovery"`
	Objectives Objectives `yaml:"objectives"`
}

func ReadLocal(path string) (*Local, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening config file: %w", err)
	}
	defer file.Close()
	l := &Local{}
	err = yaml.NewDecoder(file).Decode(l)
	if err != nil {
		return nil, fmt.Errorf("decoding config file: %w", err)
	}
	return l, nil
}
