// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package users

import (
	"fmt"
	"logbook/cmd/users/endpoints"
	"net/http"
)

type Pool interface {
	Host() (string, error)
}

type Client struct {
	p Pool
}

func NewClient(p Pool) *Client {
	return &Client{p: p}
}
