// Code generated by gohandlers v0.37.0. DO NOT EDIT.

package users

import (
	"fmt"
	"logbook/cmd/users/endpoints"
	"net/http"
)

type Interface interface {
	CreateUser(*endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error)
}

type Mock struct {
	CreateUserFunc func(*endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error)
}

func (m *Mock) CreateUser(bq *endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error) {
	if m.CreateUserFunc == nil {
		return nil, fmt.Errorf("not implemented: CreateUser")
	}
	return m.CreateUserFunc(bq)
}

type Pool interface {
	Host() (string, error)
}

type Client struct {
	p Pool
}

func NewClient(p Pool) *Client {
	return &Client{p: p}
}

func (c *Client) CreateUser(bq *endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("selecting host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("building request: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("sending: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	bs := &endpoints.CreateUserResponse{}
	err = bs.Parse(rs)
	if err != nil {
		return nil, fmt.Errorf("parsing response: %w", err)
	}
	return bs, nil
}
