// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package users

import "logbook/cmd/users/endpoints"

type Interface interface {
	CreateUser(*endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error)
}

type Mock struct {
}

func (m *Mock) CreateUser(*endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error) {
	return nil, nil
}
