// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package registry

import (
	"logbook/cmd/registry/endpoints"
	"net/http"
)

type Interface interface {
	ListInstances(*endpoints.ListInstancesRequest) (*endpoints.ListInstancesResponse, error)
	RecheckInstance(*endpoints.RecheckInstanceRequest) (*http.Response, error)
	RegisterInstance(*endpoints.RegisterInstanceRequest) (*endpoints.RegisterInstanceResponse, error)
}

type Mock struct {
}

func (m *Mock) ListInstances(*endpoints.ListInstancesRequest) (*endpoints.ListInstancesResponse, error) {
	return nil, nil
}

func (m *Mock) RecheckInstance(*endpoints.RecheckInstanceRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) RegisterInstance(*endpoints.RegisterInstanceRequest) (*endpoints.RegisterInstanceResponse, error) {
	return nil, nil
}
