// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package endpoints

import (
	"bytes"
	"encoding/json"
	"fmt"
	"mime"
	"net/http"
	"strings"
)

func join(segments ...string) string {
	url := ""
	for i, segment := range segments {
		if i != 0 && !strings.HasPrefix(segment, "/") {
			url += "/"
		}
		url += segment
	}
	return url
}

func (bq TagAssignRequest) Build(host string) (*http.Request, error) {
	uri := "/tag-assign"
	body := bytes.NewBuffer([]byte{})
	err := json.NewEncoder(body).Encode(bq)
	if err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	r, err := http.NewRequest("POST", join(host, uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", mime.TypeByExtension(".json"))
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}

func (bq *TagAssignRequest) Parse(rq *http.Request) error {
	err := json.NewDecoder(rq.Body).Decode(bq)
	if err != nil {
		return fmt.Errorf("decoding body: %w", err)
	}
	return nil
}

func (bq TagCreationRequest) Build(host string) (*http.Request, error) {
	uri := "/tag-creation"
	body := bytes.NewBuffer([]byte{})
	err := json.NewEncoder(body).Encode(bq)
	if err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	r, err := http.NewRequest("POST", join(host, uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", mime.TypeByExtension(".json"))
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}

func (bq *TagCreationRequest) Parse(rq *http.Request) error {
	err := json.NewDecoder(rq.Body).Decode(bq)
	if err != nil {
		return fmt.Errorf("decoding body: %w", err)
	}
	return nil
}
