// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"TagAssign":   {Method: "POST", Path: "/tag-assign", Ref: pu.TagAssign},
		"TagCreation": {Method: "POST", Path: "/tag-creation", Ref: pu.TagCreation},
	}
}
