// Code generated by gohandlers v0.13.2. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (en *Endpoints) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"TagAssign":   {Method: "POST", Path: "/tag-assign", Ref: en.TagAssign},
		"TagCreation": {Method: "GET", Path: "/tag-creation", Ref: en.TagCreation},
	}
}
