// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq TagAssignRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Subject.Validate(); err != nil {
		errs["subject"] = err
	}
	if err := bq.Tid.Validate(); err != nil {
		errs["tid"] = err
	}
	return
}

func (bq TagCreationRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Title.Validate(); err != nil {
		errs["title"] = err
	}
	return
}
