// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

func (bq TagAssignRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Subject.Validate(); issue != nil {
		issues["subject"] = issue
	}
	if issue := bq.Tid.Validate(); issue != nil {
		issues["tid"] = issue
	}
	return
}

func (bq TagCreationRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Title.Validate(); issue != nil {
		issues["title"] = issue
	}
	return
}
