// Code generated by gohandlers v0.31.0. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"DelegateObjective":   {Method: "POST", Path: "/delegate-objective", Ref: pu.DelegateObjective},
		"ListDelegationChain": {Method: "GET", Path: "/list-delegation-chain/{subject}", Ref: pu.ListDelegationChain},
		"RemoveDelegation":    {Method: "POST", Path: "/remove-delegation", Ref: pu.RemoveDelegation},
	}
}
