// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

func (bq DelegateObjectiveRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Delegator.Validate(); issue != nil {
		issues["delegator"] = issue
	}
	if issue := bq.Delegee.Validate(); issue != nil {
		issues["delegee"] = issue
	}
	if issue := bq.Objective.Validate(); issue != nil {
		issues["objective"] = issue
	}
	return
}

func (bq ListDelegationChainRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Subject.Validate(); issue != nil {
		issues["subject"] = issue
	}
	return
}

func (bq RemoveDelegationRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Delid.Validate(); issue != nil {
		issues["delid"] = issue
	}
	return
}
