// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq DelegateObjectiveRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Delegator.Validate(); err != nil {
		errs["delegator"] = err
	}
	if err := bq.Delegee.Validate(); err != nil {
		errs["delegee"] = err
	}
	if err := bq.Objective.Validate(); err != nil {
		errs["objective"] = err
	}
	return
}

func (bq ListDelegationChainRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Subject.Validate(); err != nil {
		errs["subject"] = err
	}
	return
}

func (bq RemoveDelegationRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Delid.Validate(); err != nil {
		errs["delid"] = err
	}
	return
}
