api:
  domain: logbook.balaasad.com

router:
  request-timeout: 2s
  write-timeout: 1s
  read-timeout: 1s
  idle-timeout: 1s
  grace-period: 1s

registry-file:
  update-period: 1s

registry:
  instance-timeout: 5s
  clearance-period: 2s
  clearance-delay: 2s

sidecar:
  recheking-ticker-delay: 500ms
  recheking-ticker-period: 1s # only needs to be smaller than registry.instance-timeout
  querying-ticker-delay: 1s
  querying-ticker-period: 1s # only needs to be smaller than registry.instance-timeout

ports:
  internal: 8080 # fixed
  registry: 8080 # fixed

  accounts: 0
  gateway: 0
  objectives: 0
  tags: 0
