api:
  domain: logbook.balaasad.com

router:
  request-timeout: 2s
  write-timeout: 1s
  read-timeout: 1s
  idle-timeout: 1s
  grace-period: 1s

service-discovery:
  update-period: 1s

ports:
  gateway: 0
  accounts: 0
  objectives: 0
  registry: 8080 # fixed
  internal: 8080 # fixed
