api:
  domain: logbook.balaasad.com

router:
  request-timeout: 2s
  write-timeout: 1s
  read-timeout: 1s
  idle-timeout: 1s
  grace-period: 1s

service-discovery:
  update-period: 1s

registry:
  instance-timeout: 5s
  clearance-period: 2s
  clearance-delay: 2s

sidecar:
  ticker-delay: 500ms
  ticker-period: 1s

ports:
  internal: 8080 # fixed
  registry: 8080 # fixed

  accounts: 0
  gateway: 0
  objectives: 0
  tags: 0
