all:
	$(MAKE) -C users
	$(MAKE) -C profiles
	$(MAKE) -C sessions
	$(MAKE) -C registration
	$(MAKE) -C auth
	$(MAKE) -C groups
	$(MAKE) -C objectives
	$(MAKE) -C pdp
	$(MAKE) -C registry
	$(MAKE) -C tags