// Code generated by gohandlers v0.4.1. DO NOT EDIT.

package endpoints

import (
	"bytes"
	"encoding/json"
	"fmt"
	"logbook/internal/utils/urls"
	"logbook/internal/web/balancer"
	"mime"
	"net/http"
)

func (bq RockCreateRequest) Build(lb *balancer.LoadBalancer) (*http.Request, error) {
	uri := "/rock-create"
	body := bytes.NewBuffer([]byte{})
	err := json.NewEncoder(body).Encode(bq)
	if err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	h, err := lb.Next()
	if err != nil {
		return nil, fmt.Errorf("lb.Next: %w", err)
	}
	r, err := http.NewRequest("POST", urls.Join(h.String(), uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", mime.TypeByExtension("json"))
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}
