// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"RockCreate": {Method: "POST", Path: "/rock-create", Ref: pr.RockCreate},
	}
}

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateObjective":   {Method: "POST", Path: "/create-objective", Ref: pu.CreateObjective},
		"GetPlacement":      {Method: "GET", Path: "/get-placement/{length}/{root}/{start}", Ref: pu.GetPlacement},
		"MarkComplete":      {Method: "PATCH", Path: "/mark-complete", Ref: pu.MarkComplete},
		"ReattachObjective": {Method: "PATCH", Path: "/reattach-objective", Ref: pu.ReattachObjective},
	}
}
