// Code generated by gohandlers v0.4.2. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"RockCreate": {Method: "POST", Path: "/rock-create", Ref: pr.RockCreate},
	}
}

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateObjective":   {Method: "POST", Path: "/create-objective", Ref: pu.CreateObjective},
		"GetPlacementArray": {Method: "GET", Path: "/get-placement-array", Ref: pu.GetPlacementArray},
		"MarkComplete":      {Method: "GET", Path: "/mark-complete", Ref: pu.MarkComplete},
		"ReattachObjective": {Method: "GET", Path: "/reattach-objective", Ref: pu.ReattachObjective},
	}
}
