// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

func (bq RockCreateRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.UserId.Validate(); issue != nil {
		issues["uid"] = issue
	}
	return
}

func (bq CreateObjectiveRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Content.Validate(); issue != nil {
		issues["content"] = issue
	}
	if issue := bq.Parent.Validate(); issue != nil {
		issues["parent"] = issue
	}
	return
}

func (bq GetPlacementRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Length.Validate(); issue != nil {
		issues["length"] = issue
	}
	if issue := bq.Root.Validate(); issue != nil {
		issues["root"] = issue
	}
	if issue := bq.Start.Validate(); issue != nil {
		issues["start"] = issue
	}
	return
}

func (bq MarkCompleteRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Completion.Validate(); issue != nil {
		issues["completion"] = issue
	}
	if issue := bq.Subject.Validate(); issue != nil {
		issues["subject"] = issue
	}
	return
}

func (bq ReattachObjectiveRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.CurrentParent.Validate(); issue != nil {
		issues["current-parent"] = issue
	}
	if issue := bq.NextParent.Validate(); issue != nil {
		issues["new-parent"] = issue
	}
	if issue := bq.Subject.Validate(); issue != nil {
		issues["subject"] = issue
	}
	return
}
