// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq RockCreateRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.UserId.Validate(); err != nil {
		errs["uid"] = err
	}
	return
}

func (bq CreateObjectiveRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Content.Validate(); err != nil {
		errs["content"] = err
	}
	if err := bq.Parent.Validate(); err != nil {
		errs["parent"] = err
	}
	return
}

func (bq GetPlacementRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Length.Validate(); err != nil {
		errs["length"] = err
	}
	if err := bq.Root.Validate(); err != nil {
		errs["root"] = err
	}
	if err := bq.Start.Validate(); err != nil {
		errs["start"] = err
	}
	return
}

func (bq MarkCompleteRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Completion.Validate(); err != nil {
		errs["completion"] = err
	}
	if err := bq.Subject.Validate(); err != nil {
		errs["subject"] = err
	}
	return
}

func (bq ReattachObjectiveRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.CurrentParent.Validate(); err != nil {
		errs["current-parent"] = err
	}
	if err := bq.NextParent.Validate(); err != nil {
		errs["new-parent"] = err
	}
	if err := bq.Subject.Validate(); err != nil {
		errs["subject"] = err
	}
	return
}
