// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO "objective" ("based", "type", "content", "creator")
    VALUES ($1, $2, $3, $4)
RETURNING
    oid, vid, based, type, content, creator, created_at
`

type CreateTaskParams struct {
	Based   pgtype.UUID
	Type    Otype
	Content string
	Creator pgtype.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Objective, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Based,
		arg.Type,
		arg.Content,
		arg.Creator,
	)
	var i Objective
	err := row.Scan(
		&i.Oid,
		&i.Vid,
		&i.Based,
		&i.Type,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :one
INSERT INTO "objective_link" ("sup_oid", "sup_vid", "sub_oid", "sub_vid")
    VALUES ($1, $2, $3, $4)
RETURNING
    lid, sup_oid, sup_vid, sub_oid, sub_vid, created_at
`

type InsertLinkParams struct {
	SupOid pgtype.UUID
	SupVid pgtype.UUID
	SubOid pgtype.UUID
	SubVid pgtype.UUID
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) (ObjectiveLink, error) {
	row := q.db.QueryRow(ctx, insertLink,
		arg.SupOid,
		arg.SupVid,
		arg.SubOid,
		arg.SubVid,
	)
	var i ObjectiveLink
	err := row.Scan(
		&i.Lid,
		&i.SupOid,
		&i.SupVid,
		&i.SubOid,
		&i.SubVid,
		&i.CreatedAt,
	)
	return i, err
}

const insertObjective = `-- name: InsertObjective :one
INSERT INTO "objective" ("vid", "based", "type", "content", "creator")
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    oid, vid, based, type, content, creator, created_at
`

type InsertObjectiveParams struct {
	Vid     pgtype.UUID
	Based   pgtype.UUID
	Type    Otype
	Content string
	Creator pgtype.UUID
}

func (q *Queries) InsertObjective(ctx context.Context, arg InsertObjectiveParams) (Objective, error) {
	row := q.db.QueryRow(ctx, insertObjective,
		arg.Vid,
		arg.Based,
		arg.Type,
		arg.Content,
		arg.Creator,
	)
	var i Objective
	err := row.Scan(
		&i.Oid,
		&i.Vid,
		&i.Based,
		&i.Type,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}

const insertVersion = `-- name: InsertVersion :one
INSERT INTO "version" ("based")
    VALUES ($1)
RETURNING
    vid, based
`

func (q *Queries) InsertVersion(ctx context.Context, based pgtype.UUID) (Version, error) {
	row := q.db.QueryRow(ctx, insertVersion, based)
	var i Version
	err := row.Scan(&i.Vid, &i.Based)
	return i, err
}

const selectEffectiveVersionOfObjective = `-- name: SelectEffectiveVersionOfObjective :one
SELECT
    "vid"
FROM
    "objective_effective_version"
WHERE
    "oid" = $1
LIMIT 1
`

func (q *Queries) SelectEffectiveVersionOfObjective(ctx context.Context, oid ObjectiveId) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, selectEffectiveVersionOfObjective, oid)
	var vid pgtype.UUID
	err := row.Scan(&vid)
	return vid, err
}

const selectObjective = `-- name: SelectObjective :one
SELECT
    "oid",
    "vid",
    "based",
    "type",
    "content",
    "creator",
    "created_at"
FROM
    "objective"
WHERE
    "oid" = $1
    AND "vid" == $2
LIMIT 1
`

type SelectObjectiveParams struct {
	Oid ObjectiveId
	Vid pgtype.UUID
}

func (q *Queries) SelectObjective(ctx context.Context, arg SelectObjectiveParams) (Objective, error) {
	row := q.db.QueryRow(ctx, selectObjective, arg.Oid, arg.Vid)
	var i Objective
	err := row.Scan(
		&i.Oid,
		&i.Vid,
		&i.Based,
		&i.Type,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}

const selectSubLinks = `-- name: SelectSubLinks :many
SELECT
    "lid",
    "sup_oid",
    "sup_vid",
    "sub_oid",
    "sub_vid",
    "created_at"
FROM
    "objective_link"
WHERE
    "sup_oid" = $1
    AND "sup_vid" = $2
LIMIT 50
`

type SelectSubLinksParams struct {
	SupOid pgtype.UUID
	SupVid pgtype.UUID
}

func (q *Queries) SelectSubLinks(ctx context.Context, arg SelectSubLinksParams) ([]ObjectiveLink, error) {
	rows, err := q.db.Query(ctx, selectSubLinks, arg.SupOid, arg.SupVid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObjectiveLink
	for rows.Next() {
		var i ObjectiveLink
		if err := rows.Scan(
			&i.Lid,
			&i.SupOid,
			&i.SupVid,
			&i.SubOid,
			&i.SubVid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTheUpperLink = `-- name: SelectTheUpperLink :one
SELECT
    "lid",
    "sup_oid",
    "sup_vid",
    "sub_oid",
    "sub_vid",
    "created_at"
FROM
    "objective_link"
WHERE
    "sub_oid" = $1
    AND "sub_vid" = $2
LIMIT 1
`

type SelectTheUpperLinkParams struct {
	SubOid pgtype.UUID
	SubVid pgtype.UUID
}

func (q *Queries) SelectTheUpperLink(ctx context.Context, arg SelectTheUpperLinkParams) (ObjectiveLink, error) {
	row := q.db.QueryRow(ctx, selectTheUpperLink, arg.SubOid, arg.SubVid)
	var i ObjectiveLink
	err := row.Scan(
		&i.Lid,
		&i.SupOid,
		&i.SupVid,
		&i.SubOid,
		&i.SubVid,
		&i.CreatedAt,
	)
	return i, err
}

const selectVersion = `-- name: SelectVersion :one
SELECT
    "vid",
    "based"
FROM
    "version"
WHERE
    "vid" = $1
LIMIT 1
`

func (q *Queries) SelectVersion(ctx context.Context, vid pgtype.UUID) (Version, error) {
	row := q.db.QueryRow(ctx, selectVersion, vid)
	var i Version
	err := row.Scan(&i.Vid, &i.Based)
	return i, err
}

const selectVersioningConfig = `-- name: SelectVersioningConfig :one
SELECT
    "oid",
    "first",
    "effective"
FROM
    "versioning_config"
WHERE
    "oid" = $1
LIMIT 1
`

func (q *Queries) SelectVersioningConfig(ctx context.Context, oid ObjectiveId) (VersioningConfig, error) {
	row := q.db.QueryRow(ctx, selectVersioningConfig, oid)
	var i VersioningConfig
	err := row.Scan(&i.Oid, &i.First, &i.Effective)
	return i, err
}
