api:
  domain: localhost

router:
  request-timeout: 2s
  write-timeout: 1s
  read-timeout: 1s
  idle-timeout: 1s
  grace-period: 1s

service-discovery:
  update-period: 30s

ports:
  gateway: :8080
  accounts: :8081
  objectives: :8082
  internal: :8090
  discovery: :8091