router:
  request-timeout: 2s
  write-timeout: 1s
  read-timeout: 1s
  idle-timeout: 1s
  grace-period: 1s

registry-file:
  update-period: 1m

registry:
  instance-timeout: 99999s # needless in local environment which spans the definitive set of instance at the start
  clearance-period: 99999s # """
  clearance-delay: 2s # builds the cache at first iteration of clearance

sidecar:
  recheking-ticker-delay: 0s
  recheking-ticker-period: 88888s # only needs to be smaller than registry.instance-timeout
  querying-ticker-delay: 4s
  querying-ticker-period: 88888s # only needs to be smaller than registry.instance-timeout

ports:
  accounts: 0
  objectives: 0
  tags: 0

  gateway: 8080
  internal: 8081
  registry: 8082
