---
router-parameters: &router-parameters
  request-timeout: 2s
  write-timeout: 100ms
  read-timeout: 100ms
  idle-timeout: 100ms
  grace-period: 100ms

common: &common
  <<: *router-parameters
  service-discovery-config: ../platform/local/files/service_discovery.json
  service-discovery-update-period: 30s
  router-public: 8080
  router-private: 8081

api_gateway:
  <<: *common
  router-public: 8083
  router-private: 8084

tasks:
  <<: *common
  router-public: 8081
  router-private: 8082

captcha:
  <<: *common
  router-public: 8085
  router-private: 8086
