@api = https://localhost:8080/api

### Get rock

GET {{api}}/objectives/rock HTTP/1.1

?? status == 200
?? body id exists
?? body id exists

### Create Task

POST {{api}}/objectives/task HTTP/1.1
Content-Type: application/json

{
    "super": "My Test Document" 
}

?? status == 200
