// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package account

import (
	"logbook/cmd/account/endpoints"
	"net/http"
)

type Interface interface {
	CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error)
	CreateProfile(*endpoints.CreateProfileRequest) (*http.Response, error)
	Login(*endpoints.LoginRequest) (*http.Response, error)
	WhoIs(*endpoints.WhoIsRequest) (*endpoints.WhoIsResponse, error)
}

type Mock struct {
}

func (m *Mock) CreateAccount(*endpoints.CreateAccountRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) CreateProfile(*endpoints.CreateProfileRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) Login(*endpoints.LoginRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) WhoIs(*endpoints.WhoIsRequest) (*endpoints.WhoIsResponse, error) {
	return nil, nil
}
