// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.links.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"logbook/models/columns"
)

const insertNewLink = `-- name: InsertNewLink :one
INSERT INTO "link"("sup_oid", "sup_vid", "sub_oid", "sub_vid")
    VALUES ($1, $2, $3, $4)
RETURNING
    sup_oid, sup_vid, sub_oid, sub_vid, created_at_original
`

type InsertNewLinkParams struct {
	SupOid columns.ObjectiveId
	SupVid columns.VersionId
	SubOid columns.ObjectiveId
	SubVid columns.VersionId
}

func (q *Queries) InsertNewLink(ctx context.Context, arg InsertNewLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, insertNewLink,
		arg.SupOid,
		arg.SupVid,
		arg.SubOid,
		arg.SubVid,
	)
	var i Link
	err := row.Scan(
		&i.SupOid,
		&i.SupVid,
		&i.SubOid,
		&i.SubVid,
		&i.CreatedAtOriginal,
	)
	return i, err
}

const insertUpdatedLink = `-- name: InsertUpdatedLink :one
INSERT INTO "link"("sup_oid", "sup_vid", "sub_oid", "sub_vid", "created_at_original")
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    sup_oid, sup_vid, sub_oid, sub_vid, created_at_original
`

type InsertUpdatedLinkParams struct {
	SupOid            columns.ObjectiveId
	SupVid            columns.VersionId
	SubOid            columns.ObjectiveId
	SubVid            columns.VersionId
	CreatedAtOriginal pgtype.Timestamp
}

func (q *Queries) InsertUpdatedLink(ctx context.Context, arg InsertUpdatedLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, insertUpdatedLink,
		arg.SupOid,
		arg.SupVid,
		arg.SubOid,
		arg.SubVid,
		arg.CreatedAtOriginal,
	)
	var i Link
	err := row.Scan(
		&i.SupOid,
		&i.SupVid,
		&i.SubOid,
		&i.SubVid,
		&i.CreatedAtOriginal,
	)
	return i, err
}

const selectSubLinks = `-- name: SelectSubLinks :many
SELECT
    sup_oid, sup_vid, sub_oid, sub_vid, created_at_original
FROM
    "link"
WHERE
    "sup_oid" = $1
    AND "sup_vid" = $2
ORDER BY
    "created_at_original" ASC
LIMIT 50
`

type SelectSubLinksParams struct {
	SupOid columns.ObjectiveId
	SupVid columns.VersionId
}

func (q *Queries) SelectSubLinks(ctx context.Context, arg SelectSubLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, selectSubLinks, arg.SupOid, arg.SupVid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.SupOid,
			&i.SupVid,
			&i.SubOid,
			&i.SubVid,
			&i.CreatedAtOriginal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUpperLinks = `-- name: SelectUpperLinks :many
SELECT
    sup_oid, sup_vid, sub_oid, sub_vid, created_at_original
FROM
    "link"
WHERE
    "sub_oid" = $1
    AND "sub_vid" = $2
LIMIT 50
`

type SelectUpperLinksParams struct {
	SubOid columns.ObjectiveId
	SubVid columns.VersionId
}

func (q *Queries) SelectUpperLinks(ctx context.Context, arg SelectUpperLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, selectUpperLinks, arg.SubOid, arg.SubVid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.SupOid,
			&i.SupVid,
			&i.SubOid,
			&i.SubVid,
			&i.CreatedAtOriginal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
