// Code generated by gohandlers v0.37.0. DO NOT EDIT.

package pdp

import (
	"fmt"
	"logbook/cmd/pdp/endpoints"
	"net/http"
)

type Interface interface {
	OidGid(*endpoints.OidGidRequest) (*http.Response, error)
	OidUid(*endpoints.OidUidRequest) (*http.Response, error)
}

type Mock struct {
	OidGidFunc func(*endpoints.OidGidRequest) (*http.Response, error)
	OidUidFunc func(*endpoints.OidUidRequest) (*http.Response, error)
}

func (m *Mock) OidGid(bq *endpoints.OidGidRequest) (*http.Response, error) {
	if m.OidGidFunc == nil {
		return nil, fmt.Errorf("not implemented: OidGid")
	}
	return m.OidGidFunc(bq)
}

func (m *Mock) OidUid(bq *endpoints.OidUidRequest) (*http.Response, error) {
	if m.OidUidFunc == nil {
		return nil, fmt.Errorf("not implemented: OidUid")
	}
	return m.OidUidFunc(bq)
}

type Pool interface {
	Host() (string, error)
}

type Client struct {
	p Pool
}

func NewClient(p Pool) *Client {
	return &Client{p: p}
}

func (c *Client) OidGid(bq *endpoints.OidGidRequest) (*http.Response, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("selecting host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("building request: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("sending: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return rs, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	return rs, nil
}

func (c *Client) OidUid(bq *endpoints.OidUidRequest) (*http.Response, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("selecting host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("building request: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("sending: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return rs, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	return rs, nil
}
