// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package pdp

import (
	"logbook/cmd/pdp/endpoints"
	"net/http"
)

type Interface interface {
	OidGid(*endpoints.OidGidRequest) (*http.Response, error)
	OidUid(*endpoints.OidUidRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) OidGid(*endpoints.OidGidRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) OidUid(*endpoints.OidUidRequest) (*http.Response, error) {
	return nil, nil
}
