@apiUrl = 127.0.0.1:8082

### Create User

POST http://{{apiUrl}}/account HTTP/1.1
Content-Type: application/json

{
    "firstname": "Tiésto",
    "lastname": "McSingleton",
    "email": "test@test.balaasad.com",
    "password": "123456789"
}

?? status == 200

### Authentication

POST http://{{apiUrl}}/session HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.balaasad.com",
    "password": "123456789"
}

?? status == 200
?? header set-cookie contains session_token

### Filling profile information

### WhoAmI

GET http://{{apiUrl}}/whoami HTTP/1.1

?? status == 200


### List bookmarks

GET http://{{apiUrl}}/bookmark HTTP/1.1
Content-Type: application/json
Authorization: TODO


### Create Task

POST {{apiUrl}}/task HTTP/1.1
Content-Type: application/json

{
    "super_task_id": "My Test Document" 
}

