###

### Registration

POST https://localhost:8081/account HTTP/1.1
Content-Type: application/json

{
    "firstname": "Tiésto",
    "lastname": "McSingleton",
    "email": "test@test.balaasad.com",
    "password": "123456789"
}

?? status == 200

### Login

POST https://localhost:8081/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.balaasad.com",
    "password": "123456789"
}

?? status == 200
?? header set-cookie includes session_token

### Filling profile information

POST https://localhost:8081/profile HTTP/1.1
Content-Type: application/json

{
    "uid": "14aec60a-5ce9-4415-bbf9-0f7b5620e576",
    "firstname": "Fiesta",
    "lastname": "McMonoton"
}

?? status == 200

### WhoAmI

GET https://localhost:8081/whoami HTTP/1.1

?? status == 200
?? body includes firstname
?? header Content-Type includes application/json

### Logout

POST https://localhost:8081/logout

?? status == 200
?? header set-cookie includes session_token

### Get rock

GET http://localhost:8081/user/rock HTTP/1.1

?? status == 200
?? body id exists
?? body id exists

### Create Task

POST http://localhost:8081/task HTTP/1.1
Content-Type: application/json

{
    "super": "My Test Document" 
}

?? status == 200
