// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package sessions

import (
	"logbook/cmd/sessions/endpoints"
	"net/http"
)

type Interface interface {
	Login(*endpoints.LoginRequest) (*http.Response, error)
	SaveCredentials(*endpoints.SaveCredentialsRequest) (*http.Response, error)
	WhoIs(*endpoints.WhoIsRequest) (*endpoints.WhoIsResponse, error)
}

type Mock struct {
}

func (m *Mock) Login(*endpoints.LoginRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) SaveCredentials(*endpoints.SaveCredentialsRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) WhoIs(*endpoints.WhoIsRequest) (*endpoints.WhoIsResponse, error) {
	return nil, nil
}
