// Code generated by gohandlers. DO NOT EDIT.

package public

import "net/http"

type HandlerInfo struct {
	Method string
	Path   string
	Ref    http.HandlerFunc
}

func (en *Endpoints) ListHandlers() map[string]HandlerInfo {
	return map[string]HandlerInfo{
		"CreateGroup":         {Method: "GET", Path: "/create-group", Ref: en.CreateGroup},
		"DelegateObjective":   {Method: "GET", Path: "/delegate-objective", Ref: en.DelegateObjective},
		"InviteCollaborators": {Method: "GET", Path: "/invite-collaborators", Ref: en.InviteCollaborators},
		"ListDelegationChain": {Method: "GET", Path: "/list-delegation-chain", Ref: en.ListDelegationChain},
		"RemoveDelegation":    {Method: "GET", Path: "/remove-delegation", Ref: en.RemoveDelegation},
		"RespondToInvite":     {Method: "GET", Path: "/respond-to-invite", Ref: en.RespondToInvite},
	}
}
