// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"SaveCredentials": {Method: "POST", Path: "/save-credentials", Ref: pr.SaveCredentials},
		"WhoIs":           {Method: "POST", Path: "/who-is", Ref: pr.WhoIs},
	}
}

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"Login":  {Method: "POST", Path: "/login", Ref: pu.Login},
		"Logout": {Method: "POST", Path: "/logout", Ref: pu.Logout},
		"WhoAmI": {Method: "GET", Path: "/who-am-i", Ref: pu.WhoAmI},
	}
}
