// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq SaveCredentialsRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Email.Validate(); err != nil {
		errs["email"] = err
	}
	if err := bq.Password.Validate(); err != nil {
		errs["password"] = err
	}
	if err := bq.Uid.Validate(); err != nil {
		errs["uid"] = err
	}
	return
}

func (bq WhoIsRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.SessionToken.Validate(); err != nil {
		errs["session_token"] = err
	}
	return
}

func (bq LoginRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Email.Validate(); err != nil {
		errs["email"] = err
	}
	if err := bq.Password.Validate(); err != nil {
		errs["password"] = err
	}
	return
}
