// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

func (bq SaveCredentialsRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Email.Validate(); issue != nil {
		issues["email"] = issue
	}
	if issue := bq.Password.Validate(); issue != nil {
		issues["password"] = issue
	}
	if issue := bq.Uid.Validate(); issue != nil {
		issues["uid"] = issue
	}
	return
}

func (bq WhoIsRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.SessionToken.Validate(); issue != nil {
		issues["session_token"] = issue
	}
	return
}

func (bq LoginRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Email.Validate(); issue != nil {
		issues["email"] = issue
	}
	if issue := bq.Password.Validate(); issue != nil {
		issues["password"] = issue
	}
	return
}
