// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"logbook/models/columns"
)

type Access struct {
	Aid       columns.AccessId
	Uid       columns.UserId
	Useragent columns.UserAgent
	Ipaddress netip.Addr
	CreatedAt pgtype.Timestamp
}

type Login struct {
	Lid       columns.LoginId
	Uid       columns.UserId
	Email     columns.Email
	Hash      string
	Deleted   bool
	CreatedAt pgtype.Timestamp
}

type SessionAccountRead struct {
	Sid       columns.SessionId
	Uid       columns.UserId
	Token     columns.SessionToken
	Deleted   bool
	CreatedAt pgtype.Timestamp
}

type SessionAccountWrite struct {
	Sid       columns.SessionId
	Uid       columns.UserId
	Token     columns.SessionToken
	Deleted   bool
	CreatedAt pgtype.Timestamp
}

type SessionStandard struct {
	Sid       columns.SessionId
	Uid       columns.UserId
	Token     columns.SessionToken
	Deleted   bool
	CreatedAt pgtype.Timestamp
}
