// Code generated by govalid. DO NOT EDIT.

package transports

import "fmt"

func (i InviteResponse) Validate() error {
	switch i {
	case Accept:
		return nil
	case Reject:
		return nil
	}
	return fmt.Errorf("invalid value")
}
