// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"logbook/models/columns"
)

type Profile struct {
	Uid       columns.UserId
	Firstname columns.HumanName
	Lastname  columns.HumanName
	CreatedAt pgtype.Timestamp
}

type User struct {
	Uid       columns.UserId
	Deleted   bool
	CreatedAt pgtype.Timestamp
}
