"**":
  export: true

"*.services":
  parent: Parent

"*.public":
  parent: Parent

"*.public.*":
  declare: endpoint
  accessors: [path, method]
  parent: Parent

"*.private":
  parent: Parent

"*.private.*":
  declare: endpoint
  accessors: [path, method]
  parent: Parent
