"*":
  accessors: [path]
  export: true

"*.services":
  parent: Parent

"*.services.*":
  accessors: [path]
  export: true
  parent: Parent

"*.services.*.endpoints":
  parent: Parent

"*.services.*.endpoints.*":
  accessors: [path, method]
  parent: Parent
