// Code generated by gohandlers v0.4.1. DO NOT EDIT.

package endpoints

import (
	"fmt"
	"logbook/internal/utils/urls"
	"logbook/internal/web/balancer"
	"net/http"
	"strings"
)

func (bq CheckMembershipRequest) Build(lb *balancer.LoadBalancer) (*http.Request, error) {
	uri := "/check-membership/{uid}/{gid}"
	uri = strings.Replace(uri, "{gid}", string(bq.Gid), 1)
	uri = strings.Replace(uri, "{uid}", string(bq.Uid), 1)
	h, err := lb.Next()
	if err != nil {
		return nil, fmt.Errorf("lb.Next: %w", err)
	}
	r, err := http.NewRequest("GET", urls.Join(h.String(), uri), nil)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	return r, nil
}
