// Code generated by gohandlers v0.2.1. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CheckMembership": {Method: "GET", Path: "/check-membership/{uid}/{gid}", Ref: pr.CheckMembership},
	}
}
func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateGroup":         {Method: "POST", Path: "/create-group", Ref: pu.CreateGroup},
		"DelegateObjective":   {Method: "GET", Path: "/delegate-objective", Ref: pu.DelegateObjective},
		"InviteCollaborators": {Method: "GET", Path: "/invite-collaborators", Ref: pu.InviteCollaborators},
		"ListDelegationChain": {Method: "GET", Path: "/list-delegation-chain", Ref: pu.ListDelegationChain},
		"RemoveDelegation":    {Method: "GET", Path: "/remove-delegation", Ref: pu.RemoveDelegation},
		"RespondToInvite":     {Method: "POST", Path: "/respond-to-invite", Ref: pu.RespondToInvite},
	}
}
