// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CheckMembership":         {Method: "GET", Path: "/check-membership/{gid}/{uid}", Ref: pr.CheckMembership},
		"CheckMembershipEventual": {Method: "GET", Path: "/check-membership-eventual/{gid}/{uid}", Ref: pr.CheckMembershipEventual},
	}
}

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateGroup":          {Method: "POST", Path: "/create-group", Ref: pu.CreateGroup},
		"InviteMembers":        {Method: "POST", Path: "/invite-members/{gid}", Ref: pu.InviteMembers},
		"RespondToGroupInvite": {Method: "POST", Path: "/respond-to-group-invite", Ref: pu.RespondToGroupInvite},
		"RespondToUserInvite":  {Method: "POST", Path: "/respond-to-user-invite", Ref: pu.RespondToUserInvite},
	}
}
