// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq CheckMembershipRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Gid.Validate(); err != nil {
		errs["gid"] = err
	}
	if err := bq.Uid.Validate(); err != nil {
		errs["uid"] = err
	}
	return
}

func (bq CheckMembershipEventualRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Gid.Validate(); err != nil {
		errs["gid"] = err
	}
	if err := bq.Uid.Validate(); err != nil {
		errs["uid"] = err
	}
	return
}

func (bq CreateGroupRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Name.Validate(); err != nil {
		errs["name"] = err
	}
	return
}

func (bq InviteMembersRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Gid.Validate(); err != nil {
		errs["gid"] = err
	}
	if err := bq.GroupTypeMembers.Validate(); err != nil {
		errs["user-type-members"] = err
	}
	if err := bq.UserTypeMembers.Validate(); err != nil {
		errs["group-type-members"] = err
	}
	return
}

func (bq RespondToGroupInviteRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Ginvid.Validate(); err != nil {
		errs["ginvid"] = err
	}
	if err := bq.MemberType.Validate(); err != nil {
		errs["member-type"] = err
	}
	if err := bq.Response.Validate(); err != nil {
		errs["response"] = err
	}
	return
}

func (bq RespondToUserInviteRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Ginvid.Validate(); err != nil {
		errs["ginvid"] = err
	}
	if err := bq.MemberType.Validate(); err != nil {
		errs["member-type"] = err
	}
	if err := bq.Response.Validate(); err != nil {
		errs["response"] = err
	}
	return
}
