// Code generated by gohandlers v0.15.2. DO NOT EDIT.

package endpoints

import (
	"encoding/json"
	"fmt"
	"mime"
	"net/http"
)

func (bs CreateUserResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", mime.TypeByExtension(".json"))
	w.WriteHeader(http.StatusOK)
	err := json.NewEncoder(w).Encode(bs)
	if err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *CreateUserResponse) Parse(rs *http.Response) error {
	ct := rs.Header.Get("Content-Type")
	if ct != mime.TypeByExtension(".json") {
		return fmt.Errorf("unsupported Content-Type: %s", ct)
	}
	err := json.NewDecoder(rs.Body).Decode(bs)
	if err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}
