// Code generated by gohandlers v0.17.0. DO NOT EDIT.

package endpoints

import (
	"encoding/json"
	"fmt"
	"mime"
	"net/http"
	"strings"
)

func join(segments ...string) string {
	url := ""
	for i, segment := range segments {
		if i != 0 && !strings.HasPrefix(segment, "/") {
			url += "/"
		}
		url += segment
	}
	return url
}

func (bq CreateUserRequest) Build(host string) (*http.Request, error) {
	uri := "/create-user"
	r, err := http.NewRequest("POST", join(host, uri), nil)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	return r, nil
}

func (bq *CreateUserRequest) Parse(rq *http.Request) error {
	return nil
}

func (bs CreateUserResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", mime.TypeByExtension(".json"))
	w.WriteHeader(http.StatusOK)
	err := json.NewEncoder(w).Encode(bs)
	if err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *CreateUserResponse) Parse(rs *http.Response) error {
	ct := rs.Header.Get("Content-Type")
	if ct != mime.TypeByExtension(".json") {
		return fmt.Errorf("unsupported Content-Type: %s", ct)
	}
	err := json.NewDecoder(rs.Body).Decode(bs)
	if err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}
