// Code generated by gohandlers v0.34.0. DO NOT EDIT.

package endpoints

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"

	"github.com/ufukty/gohandlers/pkg/gohandlers"
)

func (pr *Private) ListHandlers() map[string]gohandlers.HandlerInfo {
	return map[string]gohandlers.HandlerInfo{
		"CreateUser": {Method: "POST", Path: "/create-user", Ref: pr.CreateUser},
	}
}

func join(segments ...string) string {
	url := ""
	for i, segment := range segments {
		if i != 0 && !strings.HasPrefix(segment, "/") {
			url += "/"
		}
		url += segment
	}
	return url
}

func (bq CreateUserRequest) Build(host string) (*http.Request, error) {
	uri := "/create-user"
	body := bytes.NewBuffer([]byte{})
	if err := json.NewEncoder(body).Encode(bq); err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	r, err := http.NewRequest("POST", join(host, uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", "application/json")
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}

func (bq *CreateUserRequest) Parse(rq *http.Request) error {
	if !strings.HasPrefix(rq.Header.Get("Content-Type"), "application/json") {
		return fmt.Errorf("invalid content type for request: %s", rq.Header.Get("Content-Type"))
	}
	if err := json.NewDecoder(rq.Body).Decode(bq); err != nil {
		return fmt.Errorf("decoding body: %w", err)
	}
	return nil
}

func (bq CreateUserRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Birthday.Validate(); issue != nil {
		issues["birthday"] = issue
	}
	if issue := bq.Country.Validate(); issue != nil {
		issues["country"] = issue
	}
	if issue := bq.Email.Validate(); issue != nil {
		issues["email"] = issue
	}
	if issue := bq.Firstname.Validate(); issue != nil {
		issues["firstname"] = issue
	}
	if issue := bq.Handle.Validate(); issue != nil {
		issues["handle"] = issue
	}
	if issue := bq.Lastname.Validate(); issue != nil {
		issues["lastname"] = issue
	}
	if issue := bq.Password.Validate(); issue != nil {
		issues["password"] = issue
	}
	if issue := bq.Phone.Validate(); issue != nil {
		issues["phone"] = issue
	}
	return
}

func (bs CreateUserResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(bs); err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *CreateUserResponse) Parse(rs *http.Response) error {
	if !strings.HasPrefix(rs.Header.Get("Content-Type"), "application/json") {
		return fmt.Errorf("invalid content type for request: %s", rs.Header.Get("Content-Type"))
	}
	if err := json.NewDecoder(rs.Body).Decode(bs); err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}
