// Code generated by gohandlers v0.17.0. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateUser": {Method: "POST", Path: "/create-user", Ref: pr.CreateUser},
	}
}
