// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq CreateUserRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Birthday.Validate(); err != nil {
		errs["birthday"] = err
	}
	if err := bq.Country.Validate(); err != nil {
		errs["country"] = err
	}
	if err := bq.Email.Validate(); err != nil {
		errs["email"] = err
	}
	if err := bq.Firstname.Validate(); err != nil {
		errs["firstname"] = err
	}
	if err := bq.Handle.Validate(); err != nil {
		errs["handle"] = err
	}
	if err := bq.Lastname.Validate(); err != nil {
		errs["lastname"] = err
	}
	if err := bq.Password.Validate(); err != nil {
		errs["password"] = err
	}
	if err := bq.Phone.Validate(); err != nil {
		errs["phone"] = err
	}
	return
}
