// Code generated by gohandlers v0.30.0. DO NOT EDIT.

package endpoints

func (bq CreateUserRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Birthday.Validate(); issue != nil {
		issues["birthday"] = issue
	}
	if issue := bq.Country.Validate(); issue != nil {
		issues["country"] = issue
	}
	if issue := bq.Email.Validate(); issue != nil {
		issues["email"] = issue
	}
	if issue := bq.Firstname.Validate(); issue != nil {
		issues["firstname"] = issue
	}
	if issue := bq.Handle.Validate(); issue != nil {
		issues["handle"] = issue
	}
	if issue := bq.Lastname.Validate(); issue != nil {
		issues["lastname"] = issue
	}
	if issue := bq.Password.Validate(); issue != nil {
		issues["password"] = issue
	}
	if issue := bq.Phone.Validate(); issue != nil {
		issues["phone"] = issue
	}
	return
}
