// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Access struct {
	Uid       UserId
	Useragent pgtype.Text
	Ipaddress netip.Addr
	CreatedAt pgtype.Timestamp
}

type User struct {
	Uid       UserId
	Email     string
	Hash      string
	CreatedAt pgtype.Timestamp
}
