// Code generated by govalid. DO NOT EDIT.

package models

import "fmt"

func (s Service) Validate() error {
	switch s {
	case Account:
		return nil
	case Auth:
		return nil
	case Discovery:
		return nil
	case Groups:
		return nil
	case Internal:
		return nil
	case Objectives:
		return nil
	case Registry:
		return nil
	case Tags:
		return nil
	}
	return fmt.Errorf("invalid value")
}
