// Code generated by govalid. DO NOT EDIT.

package models

import "fmt"

func (s Service) Validate() error {
	switch s {
	case Auth:
		return nil
	case Discovery:
		return nil
	case Groups:
		return nil
	case Internal:
		return nil
	case Objectives:
		return nil
	case Pdp:
		return nil
	case Profiles:
		return nil
	case Registration:
		return nil
	case Registry:
		return nil
	case Sessions:
		return nil
	case Tags:
		return nil
	case Users:
		return nil
	}
	return fmt.Errorf("invalid value")
}
