// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateProfile": {Method: "POST", Path: "/create-profile", Ref: pr.CreateProfile},
	}
}
