// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq CreateProfileRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Firstname.Validate(); err != nil {
		errs["firstname"] = err
	}
	if err := bq.Lastname.Validate(); err != nil {
		errs["lastname"] = err
	}
	if err := bq.Uid.Validate(); err != nil {
		errs["uid"] = err
	}
	return
}
