// Code generated by gohandlers v0.30.0. DO NOT EDIT.

package endpoints

func (bq CreateProfileRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Firstname.Validate(); issue != nil {
		issues["firstname"] = issue
	}
	if issue := bq.Lastname.Validate(); issue != nil {
		issues["lastname"] = issue
	}
	if issue := bq.Uid.Validate(); issue != nil {
		issues["uid"] = issue
	}
	return
}
