// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bookmark struct {
	User      UserId
	Oid       ObjectiveId
	Vid       VersionId
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type ComputedToBottom struct {
	Oid   ObjectiveId
	Vid   VersionId
	Depth int32
}

type ComputedToTop struct {
	Oid                    ObjectiveId
	Vid                    VersionId
	DependenciesAreCleared bool
	AllCleared             bool
	Degree                 int32
	CompletedSubtasks      int32
}

type Objective struct {
	Oid       ObjectiveId
	Vid       VersionId
	Based     VersionId
	Content   string
	Creator   UserId
	CreatedAt pgtype.Timestamp
}

type ObjectiveCompletion struct {
	Oid       ObjectiveId
	Vid       VersionId
	Actor     UserId
	Completed bool
	CreatedAt pgtype.Timestamp
}

type ObjectiveDeleted struct {
	Oid       ObjectiveId
	Vid       VersionId
	DeletedBy UserId
	DeletedAt pgtype.Timestamp
}

type ObjectiveEffectiveVersion struct {
	Oid ObjectiveId
	Vid VersionId
}

type ObjectiveLink struct {
	Lid       LinkId
	SupOid    ObjectiveId
	SupVid    VersionId
	SubOid    ObjectiveId
	SubVid    VersionId
	Creator   UserId
	CreatedAt pgtype.Timestamp
}

type ObjectiveView struct {
	Oid           ObjectiveId
	Vid           VersionId
	Viewer        UserId
	Degree        int32
	Depth         int32
	Ready         bool
	CompletionPct float64
	Fold          bool
}

type OpObjectiveAttachSubobjective struct {
	Opid      OperationId
	Actor     UserId
	SupOid    ObjectiveId
	SupVid    VersionId
	SubOid    ObjectiveId
	SubVid    VersionId
	CreatedAt pgtype.Timestamp
}

type OpObjectiveContentUpdate struct {
	Opid      OperationId
	Actor     UserId
	Oid       ObjectiveId
	Vid       VersionId
	Content   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type OpObjectiveCreate struct {
	Opid      OperationId
	Actor     UserId
	Poid      ObjectiveId
	Pvid      VersionId
	Content   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type OpObjectiveDelete struct {
	Opid      OperationId
	Actor     UserId
	Oid       ObjectiveId
	Vid       VersionId
	CreatedAt pgtype.Timestamp
}

type OpObjectiveUpdateCompletion struct {
	Opid      OperationId
	Actor     UserId
	Oid       ObjectiveId
	Vid       VersionId
	Completed bool
	CreatedAt pgtype.Timestamp
}

type Version struct {
	Vid   VersionId
	Based VersionId
}

type VersioningConfig struct {
	Oid       ObjectiveId
	First     VersionId
	Effective VersionId
}
