// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"logbook/models/columns"
)

type OpStatus string

const (
	OpStatusReceived OpStatus = "received"
	OpStatusAccepted OpStatus = "accepted"
	OpStatusRejected OpStatus = "rejected"
)

func (e *OpStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OpStatus(s)
	case string:
		*e = OpStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OpStatus: %T", src)
	}
	return nil
}

type NullOpStatus struct {
	OpStatus OpStatus
	Valid    bool // Valid is true if OpStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOpStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OpStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OpStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOpStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OpStatus), nil
}

type OpType string

const (
	OpTypeCheckout               OpType = "checkout"
	OpTypeObjCompletion          OpType = "obj_completion"
	OpTypeObjContent             OpType = "obj_content"
	OpTypeObjCreateSubtask       OpType = "obj_create_subtask"
	OpTypeObjDelete              OpType = "obj_delete"
	OpTypeObjAttach              OpType = "obj_attach"
	OpTypeObjDetach              OpType = "obj_detach"
	OpTypeObjReorder             OpType = "obj_reorder"
	OpTypeUsrRegister            OpType = "usr_register"
	OpTypeTransitive             OpType = "transitive"
	OpTypeDoubleTransitiveMerger OpType = "double_transitive_merger"
)

func (e *OpType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OpType(s)
	case string:
		*e = OpType(s)
	default:
		return fmt.Errorf("unsupported scan type for OpType: %T", src)
	}
	return nil
}

type NullOpType struct {
	OpType OpType
	Valid  bool // Valid is true if OpType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOpType) Scan(value interface{}) error {
	if value == nil {
		ns.OpType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OpType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOpType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OpType), nil
}

type Active struct {
	Oid columns.ObjectiveId
	Vid columns.VersionId
}

type Bookmark struct {
	Bid         interface{}
	Uid         columns.UserId
	Oid         columns.ObjectiveId
	Vid         columns.VersionId
	DisplayName pgtype.Text
	IsRock      bool
	CreatedAt   pgtype.Timestamp
}

type ComputedProp struct {
	Propid    interface{}
	Content   string
	Creator   columns.UserId
	CreatedAt pgtype.Timestamp
}

type ComputedToTop struct {
	Oid               columns.ObjectiveId
	Vid               columns.VersionId
	Viewer            columns.UserId
	IsSolo            bool
	IsCompleted       bool
	Index             int32
	SubtreeSize       int32
	CompletedSubitems int32
}

type Link struct {
	SupOid columns.ObjectiveId
	SupVid columns.VersionId
	SubOid columns.ObjectiveId
	SubVid columns.VersionId
}

type Objective struct {
	Oid       columns.ObjectiveId
	Vid       columns.VersionId
	Based     columns.VersionId
	CreatedBy columns.OperationId
	Props     interface{}
	CreatedAt pgtype.Timestamp
}

type ObjectiveViewPref struct {
	Uid  columns.UserId
	Oid  columns.ObjectiveId
	Fold bool
}

type OpCheckout struct {
	ID   pgtype.UUID
	Opid columns.OperationId
	To   columns.VersionId
}

type OpDoubleTransitiveMerger struct {
	ID     pgtype.UUID
	Opid   columns.OperationId
	First  columns.OperationId
	Second columns.OperationId
}

type OpObjAttach struct {
	ID        pgtype.UUID
	Opid      columns.OperationId
	Child     columns.ObjectiveId
	Newparent columns.ObjectiveId
}

type OpObjCompletion struct {
	ID        pgtype.UUID
	Opid      columns.OperationId
	Completed bool
}

type OpObjContent struct {
	ID      pgtype.UUID
	Opid    columns.OperationId
	Content pgtype.Text
}

type OpObjCreateSubtask struct {
	ID      pgtype.UUID
	Opid    columns.OperationId
	Content pgtype.Text
}

type OpObjDetach struct {
	ID        pgtype.UUID
	Opid      columns.OperationId
	Child     columns.ObjectiveId
	Newparent columns.ObjectiveId
}

type OpObjReorder struct {
	ID        pgtype.UUID
	Opid      columns.OperationId
	Child     columns.ObjectiveId
	Moveafter columns.ObjectiveId
}

type OpTransitive struct {
	ID    pgtype.UUID
	Opid  columns.OperationId
	Cause columns.OperationId
}

type Operation struct {
	Opid       columns.OperationId
	Subjectoid columns.ObjectiveId
	Subjectvid columns.VersionId
	Actor      columns.UserId
	OpType     OpType
	OpStatus   OpStatus
	CreatedAt  pgtype.Timestamp
}
