// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"logbook/models/columns"
)

type Active struct {
	Oid columns.ObjectiveId
	Vid columns.VersionId
}

type Bookmark struct {
	Bid         interface{}
	Uid         columns.UserId
	Oid         columns.ObjectiveId
	Vid         columns.VersionId
	DisplayName pgtype.Text
	IsRock      bool
	CreatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type ComputedToBottom struct {
	Oid   columns.ObjectiveId
	Vid   columns.VersionId
	Depth int32
}

type ComputedToTop struct {
	Oid                    columns.ObjectiveId
	Vid                    columns.VersionId
	DependenciesAreCleared bool
	AllCleared             bool
	Degree                 int32
	CompletedSubtasks      int32
}

type Objective struct {
	Oid       columns.ObjectiveId
	Vid       columns.VersionId
	Based     columns.VersionId
	Content   string
	Creator   columns.UserId
	CreatedAt pgtype.Timestamp
}

type ObjectiveCompletion struct {
	Oid       columns.ObjectiveId
	Vid       columns.VersionId
	Actor     columns.UserId
	Completed bool
	CreatedAt pgtype.Timestamp
}

type ObjectiveLink struct {
	Lid       columns.LinkId
	SupOid    columns.ObjectiveId
	SupVid    columns.VersionId
	SubOid    columns.ObjectiveId
	SubVid    columns.VersionId
	Creator   columns.UserId
	CreatedAt pgtype.Timestamp
}

type ObjectiveView struct {
	Oid           columns.ObjectiveId
	Vid           columns.VersionId
	Viewer        columns.UserId
	Degree        int32
	Depth         int32
	Ready         bool
	CompletionPct float64
	Fold          bool
}

type OpObjectiveAttachSubobjective struct {
	Opid      columns.OperationId
	Actor     columns.UserId
	SupOid    columns.ObjectiveId
	SupVid    columns.VersionId
	SubOid    columns.ObjectiveId
	SubVid    columns.VersionId
	CreatedAt pgtype.Timestamp
}

type OpObjectiveContentUpdate struct {
	Opid      columns.OperationId
	Actor     columns.UserId
	Oid       columns.ObjectiveId
	Vid       columns.VersionId
	Content   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type OpObjectiveCreate struct {
	Opid      columns.OperationId
	Actor     columns.UserId
	Poid      columns.ObjectiveId
	Pvid      columns.VersionId
	Content   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type OpObjectiveDelete struct {
	Opid      columns.OperationId
	Actor     columns.UserId
	Oid       columns.ObjectiveId
	Vid       columns.VersionId
	CreatedAt pgtype.Timestamp
}

type OpObjectiveUpdateCompletion struct {
	Opid      columns.OperationId
	Actor     columns.UserId
	Oid       columns.ObjectiveId
	Vid       columns.VersionId
	Completed bool
	CreatedAt pgtype.Timestamp
}

type Version struct {
	Vid   columns.VersionId
	Based columns.VersionId
}
