// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.versions.sql

package database

import (
	"context"

	"logbook/models/columns"
)

const selectActive = `-- name: SelectActive :one
SELECT
    oid, vid
FROM
    "active"
WHERE
    "oid" == $1
`

func (q *Queries) SelectActive(ctx context.Context, oid columns.ObjectiveId) (Active, error) {
	row := q.db.QueryRow(ctx, selectActive, oid)
	var i Active
	err := row.Scan(&i.Oid, &i.Vid)
	return i, err
}

const updateActiveVidForObjective = `-- name: UpdateActiveVidForObjective :one
UPDATE
    "active"
SET
    "vid" = $2
WHERE
    "oid" == $1
RETURNING
    oid, vid
`

type UpdateActiveVidForObjectiveParams struct {
	Oid columns.ObjectiveId
	Vid columns.VersionId
}

func (q *Queries) UpdateActiveVidForObjective(ctx context.Context, arg UpdateActiveVidForObjectiveParams) (Active, error) {
	row := q.db.QueryRow(ctx, updateActiveVidForObjective, arg.Oid, arg.Vid)
	var i Active
	err := row.Scan(&i.Oid, &i.Vid)
	return i, err
}
