// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.properties.sql

package database

import (
	"context"

	"logbook/models/columns"
)

const insertProperties = `-- name: InsertProperties :one
INSERT INTO "computed_props"("content", "creator")
    VALUES ($1, $2)
RETURNING
    propid, content, creator, created_at
`

type InsertPropertiesParams struct {
	Content string
	Creator columns.UserId
}

func (q *Queries) InsertProperties(ctx context.Context, arg InsertPropertiesParams) (ComputedProp, error) {
	row := q.db.QueryRow(ctx, insertProperties, arg.Content, arg.Creator)
	var i ComputedProp
	err := row.Scan(
		&i.Propid,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}

const selectProperties = `-- name: SelectProperties :one
SELECT
    propid, content, creator, created_at
FROM
    "computed_props"
WHERE
    "propid" = $1
LIMIT 1
`

func (q *Queries) SelectProperties(ctx context.Context, propid columns.PropertiesId) (ComputedProp, error) {
	row := q.db.QueryRow(ctx, selectProperties, propid)
	var i ComputedProp
	err := row.Scan(
		&i.Propid,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}
