// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.properties.sql

package database

import (
	"context"

	"logbook/models/columns"
)

const insertProperties = `-- name: InsertProperties :one
INSERT INTO "props"("content", "creator")
    VALUES ($1, $2)
RETURNING
    pid, content, creator, created_at
`

type InsertPropertiesParams struct {
	Content string
	Creator columns.UserId
}

func (q *Queries) InsertProperties(ctx context.Context, arg InsertPropertiesParams) (Props, error) {
	row := q.db.QueryRow(ctx, insertProperties, arg.Content, arg.Creator)
	var i Props
	err := row.Scan(
		&i.Pid,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}

const selectProperties = `-- name: SelectProperties :one
SELECT
    pid, content, creator, created_at
FROM
    "props"
WHERE
    "pid" = $1
LIMIT 1
`

func (q *Queries) SelectProperties(ctx context.Context, pid columns.PropertiesId) (Props, error) {
	row := q.db.QueryRow(ctx, selectProperties, pid)
	var i Props
	err := row.Scan(
		&i.Pid,
		&i.Content,
		&i.Creator,
		&i.CreatedAt,
	)
	return i, err
}
