// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.bookmark.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"logbook/models/columns"
)

const insertBookmark = `-- name: InsertBookmark :one
INSERT INTO "bookmark"("uid", "oid", "vid", "display_name", "is_rock")
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    bid, uid, oid, vid, display_name, is_rock, created_at
`

type InsertBookmarkParams struct {
	Uid         columns.UserId
	Oid         columns.ObjectiveId
	Vid         columns.VersionId
	DisplayName pgtype.Text
	IsRock      bool
}

func (q *Queries) InsertBookmark(ctx context.Context, arg InsertBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, insertBookmark,
		arg.Uid,
		arg.Oid,
		arg.Vid,
		arg.DisplayName,
		arg.IsRock,
	)
	var i Bookmark
	err := row.Scan(
		&i.Bid,
		&i.Uid,
		&i.Oid,
		&i.Vid,
		&i.DisplayName,
		&i.IsRock,
		&i.CreatedAt,
	)
	return i, err
}
