direction: right

control_area: {
  shape: sql_table

  caid: ControlAreaId
  catype: ControlAreaType
  
  root: ObjectiveId

  created_at: timestamp
  deleted_at: timestamp?
}

collaboration: {
  shape: sql_table

  coid: CollaborationId
  caid: ControlAreaId

  creator: UserId
  admin: UserId
  leader: UserId

  created_at: timestamp
  deleted_at: timestamp
}

collaborator_group: {
  shape: sql_table

  crid: CollaboratorId
  coid: CollaborationId
  gid: GroupId

  created_at: timestamp
  deleted_at: timestamp
}

collaborator_user: {
  shape: sql_table

  crid: CollaboratorId
  coid: CollaborationId
  uid: UserId

  created_at: timestamp
  deleted_at: timestamp
}

group: {
  shape: sql_table
  
  gid: GroupId
  title: string
  
  created_at: timestamp
  deleted_at: timestamp?
}

group_member_user: {
  shape: sql_table

  gmid: GroupMembershipId
  
  gid: GroupId
  member: UserId
  invite: GroupInviteId
  
  created_at: timestamp
  deleted_at: timestamp?
}

group_member_group: {
  shape: sql_table

  gmid: GroupMembershipId
  
  gid: GroupId
  member: GroupId
  invite: GroupInviteId
  
  created_at: timestamp
  deleted_at: timestamp?
}

group_invite_group: {
  shape: sql_table

  ginid: GroupInviteId
  
  inviter: UserId
  invitee: GroupId
  
  created_at: timestamp
  deleted_at: timestamp?
}

group_invite_user: {
  shape: sql_table

  ginid: GroupInviteId
  
  inviter: UserId
  invitee: UserId
  
  created_at: timestamp
  deleted_at: timestamp?
}

delegation: {
  shape: sql_table

  delid: DelegationId

  caid: ControlAreaId

  delegator: UserId
  delegee: UserId

  created_at: timestamp
  deleted_at: timestamp?
}

objective.oid -- control_area.root

control_area.caid -- delegation.caid
control_area.caid -- collaboration.caid

collaboration.coid -- collaborator_group.coid
collaboration.coid -- collaborator_user.coid

group.gid -- collaborator_group.gid

group_member_user.gid -- group.gid
group_member_group.gid -- group.gid

group_invite_group.ginid -- group_member_group.invite
group_invite_user.ginid -- group_member_user.invite