erDiagram

    USER {
        uuid user_id
        text password
    }

    USER ||--o{ BOOKMARK : ""

    BOOKMARK {
        uuid user_id
        uuid task_id
        text display_name
        %% rocks are hidden in the UI
        bool is_rock 
        date creation_date
    }

    %% a bookmark points to a root node of a work tree
    BOOKMARK ||--o{ OBJECTIVE : ""

    OPERATION {
        uuid operation_id
        uuid version_id
        uuid previous_version_id

        uuid user_id
        enum summary
        enum status

        uuid task_id
        uuid linkid

        uuid created_at
    }

    OP_COMPLETION {
        uuid operation_id
        uuid generic_operation_id
        uuid task_id 
        uuid version_id
        uuid actor
        date created_at
    }

    OPERATION ||--|| OP_COMPLETION : ""

    ROLE["enum ROLE"] {
        e OWNER
        e SUPERVISOR
        e EXECUTOR
        e GUEST
    }

    STATUS["enum STATUS"] {
        e INVITED
        e ACCEPTED
        e REJECTED
        e CANCELED
    }

    PRIVILEGE {
        uuid user_role_id 
        uuid task_id
        uuid user_id
        ROLE role
        STATUS status 
        date creation_date
        date update_date
    }

    PRIVILEGE ||--|| ROLE : ""
    PRIVILEGE ||--|| STATUS : ""

    OBJECTIVE {
        uuid task_id 
        uuid version_id

        %% "Inherit super obj, randomize else"
        uuid shardingid 
        %% "Needed for sharding."
        uuid root_task_id 

        text content

        %% "id of inherited task"
        uuid inherit_privileges 
    }


    %% Any task with custom privilege hand. can have owner/viewers/executors
    PRIVILEGE }|--|| OBJECTIVE : ""
    OBJECTIVE ||--|| OPERATION : ""

    %% recalculate every link on a tree when new viewer come" ?
    LINK {
        uuid linkid
        %% "Inherit super obj, randomize otherwise"
        uuid sharding_id 

        uuid user_id 
        uuid task_id
        uuid super_task_id

        %% "FALSE if the link is deleted by user"
        bool is_active 
        %% "TRUE if this is the first link of task with any supertask"
        bool is_primary_link 

        date creation_at
        date deleted_at
    }

    OBJECTIVE ||--|{ LINK: ""

    COMPUTED_TO_TOP {
        uuid task_id
        uuid version_id
        user viewer_id

        bool is_solo
        %% bool is_leaf
        %% "for leaf"
        bool is_completed 

        %% "inherited from inviter on task creation."
        int index 
        int depth
        %% "changes for each user. divide with degree to find completion_percentage"
        int completed_subtasks 
        %% "changes for each user. not the same with OBJECTIVE.is_completed"
        float completion_percentage 

    }

    COMPUTED_TO_BOTTOM {
        uuid task_id
        uuid version_id
        user viewer_id

        int degree
    }

    OBJECTIVE ||--|| COMPUTED_TO_BOTTOM: ""
    OBJECTIVE ||--|| COMPUTED_TO_TOP: ""
