// Code generated by gohandlers v0.14.1. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pr *Private) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"WhoIs": {Method: "POST", Path: "/who-is", Ref: pr.WhoIs},
	}
}

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateAccount": {Method: "POST", Path: "/create-account", Ref: pu.CreateAccount},
		"CreateProfile": {Method: "POST", Path: "/create-profile", Ref: pu.CreateProfile},
		"Login":         {Method: "POST", Path: "/login", Ref: pu.Login},
		"Logout":        {Method: "POST", Path: "/logout", Ref: pu.Logout},
		"WhoAmI":        {Method: "GET", Path: "/who-am-i", Ref: pu.WhoAmI},
	}
}
