// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.controlarea.sql

package database

import (
	"context"

	"logbook/models/columns"
)

const deleteControlArea = `-- name: DeleteControlArea :one
UPDATE
    "control_area"
SET
    "deleted_at" = TIMESTAMP
WHERE
    "aid" = $1
RETURNING
    aid, root, ar_type, created_at, deleted_at
`

func (q *Queries) DeleteControlArea(ctx context.Context, aid columns.AreaId) (ControlArea, error) {
	row := q.db.QueryRow(ctx, deleteControlArea, aid)
	var i ControlArea
	err := row.Scan(
		&i.Aid,
		&i.Root,
		&i.ArType,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertControlArea = `-- name: InsertControlArea :one
INSERT INTO "control_area"("root", "ar_type")
    VALUES ($1, $2)
RETURNING
    aid, root, ar_type, created_at, deleted_at
`

type InsertControlAreaParams struct {
	Root   columns.ObjectiveId
	ArType AreaType
}

func (q *Queries) InsertControlArea(ctx context.Context, arg InsertControlAreaParams) (ControlArea, error) {
	row := q.db.QueryRow(ctx, insertControlArea, arg.Root, arg.ArType)
	var i ControlArea
	err := row.Scan(
		&i.Aid,
		&i.Root,
		&i.ArType,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectControlAreaOnObjective = `-- name: SelectControlAreaOnObjective :one
SELECT
    aid, root, ar_type, created_at, deleted_at
FROM
    "control_area"
WHERE
    "root" = $1
LIMIT 1
`

func (q *Queries) SelectControlAreaOnObjective(ctx context.Context, root columns.ObjectiveId) (ControlArea, error) {
	row := q.db.QueryRow(ctx, selectControlAreaOnObjective, root)
	var i ControlArea
	err := row.Scan(
		&i.Aid,
		&i.Root,
		&i.ArType,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
