// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.properties.sql

package database

import (
	"context"

	"logbook/models/columns"
)

const insertProperties = `-- name: InsertProperties :one
INSERT INTO "props"("content", "completed", "creator", "owner")
    VALUES ($1, $2, $3, $4)
RETURNING
    pid, content, completed, creator, owner, created_at
`

type InsertPropertiesParams struct {
	Content   columns.ObjectiveContent
	Completed bool
	Creator   columns.UserId
	Owner     columns.UserId
}

func (q *Queries) InsertProperties(ctx context.Context, arg InsertPropertiesParams) (Props, error) {
	row := q.db.QueryRow(ctx, insertProperties,
		arg.Content,
		arg.Completed,
		arg.Creator,
		arg.Owner,
	)
	var i Props
	err := row.Scan(
		&i.Pid,
		&i.Content,
		&i.Completed,
		&i.Creator,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}

const selectProperties = `-- name: SelectProperties :one
SELECT
    pid, content, completed, creator, owner, created_at
FROM
    "props"
WHERE
    "pid" = $1
LIMIT 1
`

func (q *Queries) SelectProperties(ctx context.Context, pid columns.PropertiesId) (Props, error) {
	row := q.db.QueryRow(ctx, selectProperties, pid)
	var i Props
	err := row.Scan(
		&i.Pid,
		&i.Content,
		&i.Completed,
		&i.Creator,
		&i.Owner,
		&i.CreatedAt,
	)
	return i, err
}
