// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	account "logbook/cmd/account/database"
	objectives "logbook/cmd/objectives/database"
)

type Tag struct {
	Tid       interface{}
	Vid       objectives.VersionId
	Text      string
	Uid       account.UserId
	Deleted   bool
	CreatedAt pgtype.Timestamp
}

type Tagging struct {
	Tid       TagId
	Oid       objectives.ObjectiveId
	Vid       objectives.VersionId
	Deleted   bool
	CreatedAt pgtype.Timestamp
}
