// Code generated by gohandlers v0.37.0. DO NOT EDIT.

package tags

import (
	"fmt"
	"logbook/cmd/tags/endpoints"
	"net/http"
)

type Interface interface {
	TagAssign(*endpoints.TagAssignRequest) (*http.Response, error)
	TagCreation(*endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error)
}

type Mock struct {
	TagAssignFunc   func(*endpoints.TagAssignRequest) (*http.Response, error)
	TagCreationFunc func(*endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error)
}

func (m *Mock) TagAssign(bq *endpoints.TagAssignRequest) (*http.Response, error) {
	if m.TagAssignFunc == nil {
		return nil, fmt.Errorf("not implemented: TagAssign")
	}
	return m.TagAssignFunc(bq)
}

func (m *Mock) TagCreation(bq *endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error) {
	if m.TagCreationFunc == nil {
		return nil, fmt.Errorf("not implemented: TagCreation")
	}
	return m.TagCreationFunc(bq)
}

type Pool interface {
	Host() (string, error)
}

type Client struct {
	p Pool
}

func NewClient(p Pool) *Client {
	return &Client{p: p}
}

func (c *Client) TagAssign(bq *endpoints.TagAssignRequest) (*http.Response, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("selecting host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("building request: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("sending: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return rs, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	return rs, nil
}

func (c *Client) TagCreation(bq *endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("selecting host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("building request: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("sending: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	bs := &endpoints.TagCreationResponse{}
	err = bs.Parse(rs)
	if err != nil {
		return nil, fmt.Errorf("parsing response: %w", err)
	}
	return bs, nil
}
