// Code generated by gohandlers v0.35.0. DO NOT EDIT.

package tags

import (
	"fmt"
	"logbook/cmd/tags/endpoints"
	"net/http"
)

type Interface interface {
	TagAssign(*endpoints.TagAssignRequest) (*http.Response, error)
	TagCreation(*endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error)
}

type Mock struct {
}

func (m *Mock) TagAssign(*endpoints.TagAssignRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) TagCreation(*endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error) {
	return nil, nil
}

type Pool interface {
	Host() (string, error)
}

type Client struct {
	p Pool
}

func NewClient(p Pool) *Client {
	return &Client{p: p}
}

func (c *Client) TagAssign(bq *endpoints.TagAssignRequest) (*http.Response, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("Host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("Build: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("Do: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return rs, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	return rs, nil
}

func (c *Client) TagCreation(bq *endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("Host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("Build: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("Do: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	bs := &endpoints.TagCreationResponse{}
	err = bs.Parse(rs)
	if err != nil {
		return nil, fmt.Errorf("Parse: %w", err)
	}
	return bs, nil
}
