// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package tags

import (
	"logbook/cmd/tags/endpoints"
	"net/http"
)

type Interface interface {
	TagAssign(*endpoints.TagAssignRequest) (*http.Response, error)
	TagCreation(*endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error)
}

type Mock struct {
}

func (m *Mock) TagAssign(*endpoints.TagAssignRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) TagCreation(*endpoints.TagCreationRequest) (*endpoints.TagCreationResponse, error) {
	return nil, nil
}
