// Code generated by govalid. DO NOT EDIT.

package columns

import "fmt"

func (l LinkType) Validate() error {
	switch l {
	case Primary:
		return nil
	case Private:
		return nil
	case Remote:
		return nil
	}
	return fmt.Errorf("invalid value")
}
