// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package objectives

import (
	"logbook/cmd/objectives/endpoints"
	"net/http"
)

type Interface interface {
	CreateObjective(*endpoints.CreateObjectiveRequest) (*endpoints.CreateObjectiveResponse, error)
	GetPlacementArray(*endpoints.GetPlacementArrayRequest) (*endpoints.GetPlacementArrayResponse, error)
	MarkComplete(*endpoints.MarkCompleteRequest) (*endpoints.MarkCompleteResponse, error)
	ReattachObjective(*endpoints.ReattachObjectiveRequest) (*endpoints.ReattachObjectiveResponse, error)
	RockCreate(*endpoints.RockCreateRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CreateObjective(*endpoints.CreateObjectiveRequest) (*endpoints.CreateObjectiveResponse, error) {
	return nil, nil
}

func (m *Mock) GetPlacementArray(*endpoints.GetPlacementArrayRequest) (*endpoints.GetPlacementArrayResponse, error) {
	return nil, nil
}

func (m *Mock) MarkComplete(*endpoints.MarkCompleteRequest) (*endpoints.MarkCompleteResponse, error) {
	return nil, nil
}

func (m *Mock) ReattachObjective(*endpoints.ReattachObjectiveRequest) (*endpoints.ReattachObjectiveResponse, error) {
	return nil, nil
}

func (m *Mock) RockCreate(*endpoints.RockCreateRequest) (*http.Response, error) {
	return nil, nil
}
