// Code generated by gohandlers v0.35.0. DO NOT EDIT.

package profiles

import (
	"fmt"
	"logbook/cmd/profiles/endpoints"
	"net/http"
)

type Interface interface {
	CreateProfile(*endpoints.CreateProfileRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CreateProfile(*endpoints.CreateProfileRequest) (*http.Response, error) {
	return nil, nil
}

type Pool interface {
	Host() (string, error)
}

type Client struct {
	p Pool
}

func NewClient(p Pool) *Client {
	return &Client{p: p}
}

func (c *Client) CreateProfile(bq *endpoints.CreateProfileRequest) (*http.Response, error) {
	h, err := c.p.Host()
	if err != nil {
		return nil, fmt.Errorf("Host: %w", err)
	}
	rq, err := bq.Build(h)
	if err != nil {
		return nil, fmt.Errorf("Build: %w", err)
	}
	rs, err := http.DefaultClient.Do(rq)
	if err != nil {
		return nil, fmt.Errorf("Do: %w", err)
	}
	if rs.StatusCode != http.StatusOK {
		return rs, fmt.Errorf("non-200 status code: %d (%s)", rs.StatusCode, http.StatusText(rs.StatusCode))
	}
	return rs, nil
}
