// Code generated by gohandlers v0.32.0. DO NOT EDIT.

package profiles

import (
	"logbook/cmd/profiles/endpoints"
	"net/http"
)

type Interface interface {
	CreateProfile(*endpoints.CreateProfileRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CreateProfile(*endpoints.CreateProfileRequest) (*http.Response, error) {
	return nil, nil
}
