// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateAccount":    {Method: "POST", Path: "/create-account", Ref: pu.CreateAccount},
		"GetEmailGrant":    {Method: "GET", Path: "/get-email-grant", Ref: pu.GetEmailGrant},
		"GetPasswordGrant": {Method: "GET", Path: "/get-password-grant", Ref: pu.GetPasswordGrant},
		"GetPhoneGrant":    {Method: "GET", Path: "/get-phone-grant", Ref: pu.GetPhoneGrant},
	}
}
