// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (pu *Public) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"CreateAccount": {Method: "POST", Path: "/create-account", Ref: pu.CreateAccount},
	}
}
