// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq CreateAccountRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.AntiCsrfToken.Validate(); err != nil {
		errs["acsrft"] = err
	}
	if err := bq.Birthday.Validate(); err != nil {
		errs["birthday"] = err
	}
	if err := bq.Country.Validate(); err != nil {
		errs["country"] = err
	}
	if err := bq.EmailGrant.Validate(); err != nil {
		errs["email-grant"] = err
	}
	if err := bq.Firstname.Validate(); err != nil {
		errs["firstname"] = err
	}
	if err := bq.Lastname.Validate(); err != nil {
		errs["lastname"] = err
	}
	if err := bq.PasswordGrant.Validate(); err != nil {
		errs["password-grant"] = err
	}
	if err := bq.PhoneGrant.Validate(); err != nil {
		errs["phone-grant"] = err
	}
	return
}

func (bq CreateEmailGrantRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.AntiCsrfToken.Validate(); err != nil {
		errs["acsrft"] = err
	}
	if err := bq.Email.Validate(); err != nil {
		errs["email"] = err
	}
	return
}

func (bq CreatePasswordGrantRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.AntiCsrfToken.Validate(); err != nil {
		errs["acsrft"] = err
	}
	if err := bq.Password.Validate(); err != nil {
		errs["password"] = err
	}
	return
}

func (bq CreatePhoneGrantRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.AntiCsrfToken.Validate(); err != nil {
		errs["acsrft"] = err
	}
	if err := bq.Phone.Validate(); err != nil {
		errs["phone"] = err
	}
	return
}
