// Code generated by gonfique. DO NOT EDIT.

package deployment

import (
	"os"
	"time"
	"fmt"
	"gopkg.in/yaml.v3"
)

type Router struct {
	GracePeriod    time.Duration `yaml:"grace-period"`
	IdleTimeout    time.Duration `yaml:"idle-timeout"`
	ReadTimeout    time.Duration `yaml:"read-timeout"`
	RequestTimeout time.Duration `yaml:"request-timeout"`
	WriteTimeout   time.Duration `yaml:"write-timeout"`
}
type Config struct {
	Ports struct {
		Accounts   int `yaml:"accounts"`
		Gateway    int `yaml:"gateway"`
		Internal   int `yaml:"internal"`
		Objectives int `yaml:"objectives"`
		Registry   int `yaml:"registry"`
		Tags       int `yaml:"tags"`
	} `yaml:"ports"`
	Router           Router `yaml:"router"`
	ServiceDiscovery struct {
		UpdatePeriod time.Duration `yaml:"update-period"`
	} `yaml:"service-discovery"`
	Sidecar struct {
		QueryPeriod  time.Duration `yaml:"query-period"`
		TickerDelay  time.Duration `yaml:"ticker-delay"`
		TickerPeriod time.Duration `yaml:"ticker-period"`
	} `yaml:"sidecar"`
}

func ReadConfig(path string) (*Config, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening config file: %w", err)
	}
	defer file.Close()
	c := &Config{}
	err = yaml.NewDecoder(file).Decode(c)
	if err != nil {
		return nil, fmt.Errorf("decoding config file: %w", err)
	}
	return c, nil
}
