// Code generated by gonfique v2.0.0-alpha.9. DO NOT EDIT.

package deployment

import (
	"fmt"
	"os"
	"time"

	"gopkg.in/yaml.v3"
)

// exported for cors
type Cors struct {
	AllowOrigin string `yaml:"allow-origin"`
}

// exported for environment
type Environment string

// exported for ports
type Ports struct {
	Gateway      int `yaml:"gateway"`
	Internal     int `yaml:"internal"`
	Objectives   int `yaml:"objectives"`
	Pdp          int `yaml:"pdp"`
	Profiles     int `yaml:"profiles"`
	Registration int `yaml:"registration"`
	Registry     int `yaml:"registry"`
	Sessions     int `yaml:"sessions"`
	Tags         int `yaml:"tags"`
	Users        int `yaml:"users"`
}

// exported for reception
type Reception struct {
	RequestTimeout time.Duration `yaml:"request-timeout"`
}

// exported for registry
type Registry struct {
	ClearanceDelay  time.Duration `yaml:"clearance-delay"`
	ClearancePeriod time.Duration `yaml:"clearance-period"`
	InstanceTimeout time.Duration `yaml:"instance-timeout"`
}

// exported for registry-file
type RegistryFile struct {
	UpdatePeriod time.Duration `yaml:"update-period"`
}

// exported for router
type Router struct {
	GracePeriod  time.Duration `yaml:"grace-period"`
	IdleTimeout  time.Duration `yaml:"idle-timeout"`
	ReadTimeout  time.Duration `yaml:"read-timeout"`
	WriteTimeout time.Duration `yaml:"write-timeout"`
}

// exported for sidecar
type Sidecar struct {
	QueryingTickerDelay   time.Duration `yaml:"querying-ticker-delay"`
	QueryingTickerPeriod  time.Duration `yaml:"querying-ticker-period"`
	RechekingTickerDelay  time.Duration `yaml:"recheking-ticker-delay"`
	RechekingTickerPeriod time.Duration `yaml:"recheking-ticker-period"`
}

type Config struct {
	Cors         Cors         `yaml:"cors"`
	Environment  Environment  `yaml:"environment"`
	Ports        Ports        `yaml:"ports"`
	Reception    Reception    `yaml:"reception"`
	Registry     Registry     `yaml:"registry"`
	RegistryFile RegistryFile `yaml:"registry-file"`
	Router       Router       `yaml:"router"`
	Sidecar      Sidecar      `yaml:"sidecar"`
}

func ReadConfig(path string) (*Config, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening config file: %w", err)
	}
	defer file.Close()
	c := &Config{}
	err = yaml.NewDecoder(file).Decode(c)
	if err != nil {
		return nil, fmt.Errorf("decoding config file: %w", err)
	}
	return c, nil
}
