// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package groups

import (
	"logbook/cmd/groups/endpoints"
	"net/http"
)

type Interface interface {
	CheckMembership(*endpoints.CheckMembershipRequest) (*endpoints.CheckMembershipResponse, error)
	CheckMembershipEventual(*endpoints.CheckMembershipEventualRequest) (*endpoints.CheckMembershipEventualResponse, error)
	CreateGroup(*endpoints.CreateGroupRequest) (*endpoints.CreateGroupResponse, error)
	DelegateObjective(*endpoints.DelegateObjectiveRequest) (*endpoints.DelegateObjectiveResponse, error)
	InviteCollaborators(*endpoints.InviteCollaboratorsRequest) (*http.Response, error)
	ListDelegationChain(*endpoints.ListDelegationChainRequest) (*http.Response, error)
	RemoveDelegation(*endpoints.RemoveDelegationRequest) (*http.Response, error)
	RespondToInvite(*endpoints.RespondToInviteRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CheckMembership(*endpoints.CheckMembershipRequest) (*endpoints.CheckMembershipResponse, error) {
	return nil, nil
}

func (m *Mock) CheckMembershipEventual(*endpoints.CheckMembershipEventualRequest) (*endpoints.CheckMembershipEventualResponse, error) {
	return nil, nil
}

func (m *Mock) CreateGroup(*endpoints.CreateGroupRequest) (*endpoints.CreateGroupResponse, error) {
	return nil, nil
}

func (m *Mock) DelegateObjective(*endpoints.DelegateObjectiveRequest) (*endpoints.DelegateObjectiveResponse, error) {
	return nil, nil
}

func (m *Mock) InviteCollaborators(*endpoints.InviteCollaboratorsRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) ListDelegationChain(*endpoints.ListDelegationChainRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) RemoveDelegation(*endpoints.RemoveDelegationRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) RespondToInvite(*endpoints.RespondToInviteRequest) (*http.Response, error) {
	return nil, nil
}
