// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package groups

import (
	"logbook/cmd/groups/endpoints"
	"net/http"
)

type Interface interface {
	CheckMembership(*endpoints.CheckMembershipRequest) (*endpoints.CheckMembershipResponse, error)
	CheckMembershipEventual(*endpoints.CheckMembershipEventualRequest) (*endpoints.CheckMembershipEventualResponse, error)
	CreateGroup(*endpoints.CreateGroupRequest) (*endpoints.CreateGroupResponse, error)
	InviteMembers(*endpoints.InviteMembersRequest) (*http.Response, error)
	RespondToGroupInvite(*endpoints.RespondToGroupInviteRequest) (*http.Response, error)
	RespondToUserInvite(*endpoints.RespondToUserInviteRequest) (*http.Response, error)
}

type Mock struct {
}

func (m *Mock) CheckMembership(*endpoints.CheckMembershipRequest) (*endpoints.CheckMembershipResponse, error) {
	return nil, nil
}

func (m *Mock) CheckMembershipEventual(*endpoints.CheckMembershipEventualRequest) (*endpoints.CheckMembershipEventualResponse, error) {
	return nil, nil
}

func (m *Mock) CreateGroup(*endpoints.CreateGroupRequest) (*endpoints.CreateGroupResponse, error) {
	return nil, nil
}

func (m *Mock) InviteMembers(*endpoints.InviteMembersRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) RespondToGroupInvite(*endpoints.RespondToGroupInviteRequest) (*http.Response, error) {
	return nil, nil
}

func (m *Mock) RespondToUserInvite(*endpoints.RespondToUserInviteRequest) (*http.Response, error) {
	return nil, nil
}
