name: Lint & Static Analysis

on:
  push: {}
  pull_request: {}

jobs:
  go-lint:
    name: Go fmt & golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: go fmt
        working-directory: backend
        run: go fmt ./...

      - name: Install golangci-lint
        run: >
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | 
            sh -s -- -b "$(go env GOPATH)"/bin v1.58.0

      - name: golangci-lint
        working-directory: backend
        run: golangci-lint run --timeout 5m ./...

  shell-lint:
    name: Shell script linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: shellcheck **/*.sh
