// Code generated by gohandlers v0.15.1. DO NOT EDIT.

package endpoints

import (
	"bytes"
	"encoding/json"
	"fmt"
	"mime"
	"net/http"
	"strings"
)

func join(segments ...string) string {
	url := ""
	for i, segment := range segments {
		if i != 0 && !strings.HasPrefix(segment, "/") {
			url += "/"
		}
		url += segment
	}
	return url
}

func (bq ListInstancesRequest) Build(host string) (*http.Request, error) {
	uri := "/list-instances/{service}"
	encoded, err := bq.Service.ToRoute()
	if err != nil {
		return nil, fmt.Errorf("ListInstancesRequest.Service.ToRoute: %w", err)
	}
	uri = strings.Replace(uri, "{service}", encoded, 1)
	r, err := http.NewRequest("GET", join(host, uri), nil)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	return r, nil
}

func (bq *ListInstancesRequest) Parse(rq *http.Request) error {
	err := bq.Service.FromRoute(rq.PathValue("service"))
	if err != nil {
		return fmt.Errorf("ListInstancesRequest.Service.FromRoute: %w", err)
	}
	return nil
}

func (bs ListInstancesResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", mime.TypeByExtension(".json"))
	w.WriteHeader(http.StatusOK)
	err := json.NewEncoder(w).Encode(bs)
	if err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *ListInstancesResponse) Parse(rs *http.Response) error {
	ct := rs.Header.Get("Content-Type")
	if ct != mime.TypeByExtension(".json") {
		return fmt.Errorf("unsupported Content-Type: %s", ct)
	}
	err := json.NewDecoder(rs.Body).Decode(bs)
	if err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}

func (bq RecheckInstanceRequest) Build(host string) (*http.Request, error) {
	uri := "/recheck-instance"
	body := bytes.NewBuffer([]byte{})
	err := json.NewEncoder(body).Encode(bq)
	if err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	r, err := http.NewRequest("POST", join(host, uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", mime.TypeByExtension(".json"))
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}

func (bq *RecheckInstanceRequest) Parse(rq *http.Request) error {
	err := json.NewDecoder(rq.Body).Decode(bq)
	if err != nil {
		return fmt.Errorf("decoding body: %w", err)
	}
	return nil
}

func (bq RegisterInstanceRequest) Build(host string) (*http.Request, error) {
	uri := "/register-instance"
	body := bytes.NewBuffer([]byte{})
	err := json.NewEncoder(body).Encode(bq)
	if err != nil {
		return nil, fmt.Errorf("json.Encoder.Encode: %w", err)
	}
	r, err := http.NewRequest("POST", join(host, uri), body)
	if err != nil {
		return nil, fmt.Errorf("http.NewRequest: %w", err)
	}
	r.Header.Set("Content-Type", mime.TypeByExtension(".json"))
	r.Header.Set("Content-Length", fmt.Sprintf("%d", body.Len()))
	return r, nil
}

func (bq *RegisterInstanceRequest) Parse(rq *http.Request) error {
	err := json.NewDecoder(rq.Body).Decode(bq)
	if err != nil {
		return fmt.Errorf("decoding body: %w", err)
	}
	return nil
}

func (bs RegisterInstanceResponse) Write(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", mime.TypeByExtension(".json"))
	w.WriteHeader(http.StatusOK)
	err := json.NewEncoder(w).Encode(bs)
	if err != nil {
		return fmt.Errorf("encoding the body: %w", err)
	}
	return nil
}

func (bs *RegisterInstanceResponse) Parse(rs *http.Response) error {
	ct := rs.Header.Get("Content-Type")
	if ct != mime.TypeByExtension(".json") {
		return fmt.Errorf("unsupported Content-Type: %s", ct)
	}
	err := json.NewDecoder(rs.Body).Decode(bs)
	if err != nil {
		return fmt.Errorf("decoding the body: %w", err)
	}
	return nil
}
