// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (e *Endpoints) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"ListInstances":    {Method: "GET", Path: "/list-instances/{service}", Ref: e.ListInstances},
		"RecheckInstance":  {Method: "POST", Path: "/recheck-instance", Ref: e.RecheckInstance},
		"RegisterInstance": {Method: "POST", Path: "/register-instance", Ref: e.RegisterInstance},
	}
}
