// Code generated by gohandlers v0.13.1. DO NOT EDIT.

package endpoints

import "logbook/internal/web/reception"

func (en *Endpoints) ListHandlers() map[string]reception.HandlerInfo {
	return map[string]reception.HandlerInfo{
		"ListInstances":    {Method: "GET", Path: "/list-instances/{service}", Ref: en.ListInstances},
		"RecheckInstance":  {Method: "POST", Path: "/recheck-instance", Ref: en.RecheckInstance},
		"RegisterInstance": {Method: "POST", Path: "/register-instance", Ref: en.RegisterInstance},
	}
}
