// Code generated by gohandlers v0.30.0. DO NOT EDIT.

package endpoints

func (bq ListInstancesRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Service.Validate(); issue != nil {
		issues["service"] = issue
	}
	return
}

func (bq RecheckInstanceRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.InstanceId.Validate(); issue != nil {
		issues["instance-id"] = issue
	}
	if issue := bq.Service.Validate(); issue != nil {
		issues["service"] = issue
	}
	return
}

func (bq RegisterInstanceRequest) Validate() (issues map[string]any) {
	issues = map[string]any{}
	if issue := bq.Address.Validate(); issue != nil {
		issues["address"] = issue
	}
	if issue := bq.Port.Validate(); issue != nil {
		issues["port"] = issue
	}
	if issue := bq.Service.Validate(); issue != nil {
		issues["service"] = issue
	}
	if issue := bq.TLS.Validate(); issue != nil {
		issues["tls"] = issue
	}
	return
}
