// Code generated by gohandlers v0.27.3. DO NOT EDIT.

package endpoints

func (bq ListInstancesRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Service.Validate(); err != nil {
		errs["service"] = err
	}
	return
}

func (bq RecheckInstanceRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.InstanceId.Validate(); err != nil {
		errs["instance-id"] = err
	}
	if err := bq.Service.Validate(); err != nil {
		errs["service"] = err
	}
	return
}

func (bq RegisterInstanceRequest) Validate() (errs map[string]error) {
	errs = map[string]error{}
	if err := bq.Address.Validate(); err != nil {
		errs["address"] = err
	}
	if err := bq.Port.Validate(); err != nil {
		errs["port"] = err
	}
	if err := bq.Service.Validate(); err != nil {
		errs["service"] = err
	}
	if err := bq.TLS.Validate(); err != nil {
		errs["tls"] = err
	}
	return
}
